### PR TITLE
Drop invalid messages if needed

### PR DESCRIPTION
**Pull request by patsak**

### CODE REVIEW

**Comment by ewencp** [comment]
@patsak Are there cases where we expect to fail to convert the data? I'm not sure whether a setting for this makes sense -- if there's a bug in the conversion code, we should just fix that.

**Comment by patsak** [comment]
@ewencp  Producer has written message without key for example - https://github.com/confluentinc/kafka-connect-elasticsearch/blob/master/src/main/java/io/confluent/connect/elasticsearch/DataConverter.java#L56-L58
Or user make a mistake and write messages for other topic.  
In this cases connector stuck on this messages forever.

**Comment by patsak** [comment]
[clabot:check]

**Comment by patsak** [comment]
@ewencp I've retargeted branch with merge conflicts resolving and style fixes.

**Comment by ewencp** [comment]
ok to test

**Comment by ewencp** [comment]
Great, looks good. Thanks for the contribution @patsak!

**Pull request merged**
