### PR TITLE
Allow many-to-many relationship between topics and indices

### PR DESCRIPTION
**Pull request by cgetzen**
closes https://github.com/confluentinc/kafka-connect-elasticsearch/issues/333

| topic.index.map config | Current Behavior | PR Behavior |
|-|-|-|
| topic1:index1,topic2:index1 | topic1 -> index1 and topic2 -> index1 | topic1 -> index1 and topic2 -> index1 |
| topic1:index1,topic1:index2 | topic1 -> index2 | topic1 -> index1 and topic1 -> index2|

### Testing Notes
- [x] Compile and run in a real cluster to ensure behavior.

### Follow up questions
- Should this be a PR to master? 5.2.x? 5.3.x?

### CODE REVIEW

**Comment by cgetzen** [comment]
Tagging @C0urante @rhauch @cyrusv @purbon for visibility.

**Comment by cricket007** [comment]
PR should target master, by the way, not an existing release (unless feature is chosen to be backported)

**Comment by cyrusv** [comment]
> Tagging @C0urante @rhauch @cyrusv @purbon for visibility.

+ @levzem

**Comment by levzem** [comment]
@cgetzen 

we appreciate your contribution. Unfortunately, `topic.index.map` is a deprecated feature as mentioned in the documentation. We advise to use SMTs now to achieve the desired `topic.index.map` effect. It would send the wrong message by adding new functionality to a deprecated feature.

Doubly unfortunately, the only way I see to replicate this feature right now using SMTs is to have two instances of the connector running or having duplicate topics (i.e using replicator to copy a topic). I am open to any other suggestions on how we can provide this feature in a better way without having to result to either of those solutions. 

For this reason, I am going to close this PR however we can continue any further discussion in #333

**Pull request closed without merging**
