### PR TITLE
Secure Elastic Authentication

### PR DESCRIPTION
**Pull request by jdbranham**

### CODE REVIEW

**Comment by jdbranham** [comment]
[clabot:check]

**Comment by synhershko** [comment]
Hi, what is the status of this?

**Comment by cricket007** [comment]
By the way, this duplicate efforts on #77 and #111

**Comment by rhauch** [comment]
@jdbranham thanks for the contribution! We've had a number of duplicate issues and PRs, and we've addressed basic auth with #215. I'm going to close this without merging, but if you feel #215 doesn't address your requirements, please respond here or open a new issue.

Thanks, @cricket007, for helping us find all the duplicate issues. :-)

**Comment by cricket007** [comment]
@rhauch Welcome 😄 

Also #130 could be commented/closed.

**Pull request closed without merging**
