### PR TITLE
MINOR: Update docs URLs

### PR DESCRIPTION
**Pull request by tikimims**
## Problem
https://confluentinc.atlassian.net/browse/DOCS-7071

## Solution
Update documentation URL paths

##### Does this solution apply anywhere else?
- [ ] yes
- [ ] no

##### Testing done:
- [ ] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

### CODE REVIEW

**Comment by tikimims** [comment]
@confluentinc/connect-team1  Can I get a +1 on this? Also which branch should I target for this one?

cc @joel-hamill

**Review by kkonstantine — APPROVED** [review]
LGTM

**Comment by kkonstantine** [comment]
@tikimims does this apply to version independent of CP? In that case we should target `10.0.x`

**Review by joel-hamill — APPROVED** [review]

**Comment by tikimims** [comment]
@kkonstantine @joel-hamill Thank you for reviewing.

@kkonstantine I've targeted 10.0.x branch 👍

**Pull request merged**
