### PR TITLE
changed jest version and handled generics warnings

### PR DESCRIPTION
**Pull request by talaloni2**
Handled generics warnings and changed jest version to 6.3.1(in pom.xml) in order to avoid field deprecation warnings on Elasticsearch version 6.1 on
Solves this issue: #295

### CODE REVIEW

**Comment by talaloni2** [comment]
[clabot:check]

**Comment by dkirrane** [comment]
Hi could this be merged? Hitting this same issue using the latest cp-docker-images and cp-helm-chart

**Comment by talaloni2** [comment]
> Hi could this be merged? Hitting this same issue using the latest cp-docker-images 5.1.2 and cp-helm-chart

Merge is blocked because someone with write access needs to approve it for merge to happen...

**Comment by FNaughton** [comment]
Hi, looks like this PR is open for over a month. Would be great if someone could review so it can be merged. We're currently working around the issue, but this fix would certainly make life easier!

**Comment by opsnull** [comment]
@avocader Could you please review this PR ?

**Comment by the4thamigo-uk** [comment]
Is there a plan to merge this fix?

**Comment by levzem** [comment]
#295 is solved by #327, implementing the jest version upgrade as well, so I will be closing this PR. 

Please re-open if there are questions or issues. 

Thank you for your contribution @talaloni2

**Pull request closed without merging**
