### PR TITLE
Support specify pipeline as bulk parameter (#72)

### LINKED ISSUE #72: ES Ingest Pipeline support
Elasticsearch has support for [Ingest Pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/ingest.html) to perform transformations on data before it is indexed. The indexing API requires a parameter to be passed to use a pipeline:

```
PUT /myindex/type/1?pipeline=monthlyindex
{
  "date1" : "2016-04-25T12:02:01.789Z"
}
```

Would it be possible to add this as an option to the Kafka Connect Elasticsearch connector?

### PR DESCRIPTION
**Pull request by liketic**
Closes #72

### CODE REVIEW

**Comment by liketic** [comment]
Hi @ewencp , may I ask you to review this? Thanks in advance. 😃

**Comment by panda87** [comment]
Thanks @liketic for this PR! - @ewencp we excessively using kafka connect and we also want to move our logs to send to Kafka instead of directly to ES (with new pipeline API), and this PR is perfect for that purpose, can you pls take a look on this and merge it?

**Comment by tstitescardinal** [comment]
Hi @ewencp,
Will this PR be merged? Is there a timeline for adding this functionality?

**Comment by ngwwm** [comment]
Yes, please. The feature would be very useful.

**Comment by liketic** [comment]
@rhauch Could you please help to review this one? Thanks in advance.

**Comment by eder-ai** [comment]
Will this PR be merged? This functionality would be a great addition!

**Comment by perryao** [comment]
I'd love to see some conversation around this. If anyone from Confluent has some tips or feedback, that would be awesome. I'd be willing to help get this merged in any way I can.

**Comment by perryao** [comment]
@liketic I've made some updates in my fork that fix the merge conflicts and move some of this logic into the JestElasticsearchClient. @ewencp would you care to take a look? https://github.com/perryao/kafka-connect-elasticsearch/commit/076ad9faf6e2853d45573c12f33955ff4c61f271

**Comment by perryao** [comment]
@rhauch you have time to take a look at this?

**Pull request closed without merging**
