### PR TITLE
Add licenses

### PR DESCRIPTION
**Pull request by Ishiihara**

### CODE REVIEW

**Comment by Ishiihara** [comment]
@ewencp Updated the PR to include `notices` and `license.html`. I also add in maven to clean up the contents in `notices` and `licences`. Not sure this is the best way to handle this, but `mvn -P licenses-source clean package` can be used to update the licenses and notices.

**Comment by gwenshap** [comment]
there are no "notice" files for the Apache components, is this intentional?

**Comment by ewencp** [comment]
@Ishiihara LGTM

**Comment by ewencp** [comment]
@gwenshap They may not be including the NOTICE in their binary distro.

**Pull request merged**
